Repository HuckathonteamD/chat-app, pull requests merged in 2022-11, with the labels that each got.

#13 チャンネルフォロー機能追加、チャンネル一覧表示時の詳細表示追加
  app.py
  models.py
  static/css/modal.css
  static/js/follow-channel.js
  static/js/pagination.js
  static/js/update-channel.js
  templates/base.html
  templates/detail.html
  templates/error/base.html
  templates/index.html
  templates/modal/follow-channel.html
  templates/registration/base.html
Labels: frontend, backend

#15 メッセージ編集機能追加、メッセージ表示方法をJSに変更
  app.py
  models.py
  static/css/detail.css
  static/js/follow-channel.js
  static/js/message-edit.js
  static/js/update-channel.js
  templates/detail.html
  templates/modal/delete-message.html
  templates/modal/update-message.html
  util/dateformat.py
Labels: frontend, backend

#17 ON DELETE CASCADEの有効化
  app.py
  init.sql
  models.py
  static/js/message-edit.js
  templates/detail.html
Labels: backend

#26 リアクション機能暫定版を追加
  app.py
  init.sql
  models.py
  static/css/detail.css
  static/img/reaction/arigatougozaimasu.png
  static/img/reaction/douidesu.png
  static/img/reaction/iine.png
  static/img/reaction/kami.png
  static/img/reaction/kanzendoui.png
  static/img/reaction/kanzenrikai.png
  static/img/reaction/mondainasi.png
  static/img/reaction/otukaresamadesu.png
  static/img/reaction/shoutishimashita.png
  static/img/reaction/siranakatta.png
  static/img/reaction/subarashiidesu.png
  static/img/reaction/sutekidesu.png
  static/img/reaction/yoroshikuonegaishimasu.png
  static/js/message-edit.js
  static/js/update-channel.js
  templates/detail.html
  templates/modal/add-reaction.html
Labels: frontend, backend

#30 Feature#29
  static/css/sign-up.css
  static/css/styles.css
  static/img/signinBackgroudPic.jpg
  templates/registration/base.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: frontend

#32 Feature#25
  .vscode/settings.json
  app.py
  models.py
  static/css/login.css
  static/css/my_page.css
  static/css/styles.css
  static/img/Channel-Ring.png
  static/img/Channel-chatIcon.png
  static/img/Home-Black.png
  static/img/Home-White.png
  static/img/Logout-Black.png
  static/img/Logout-White.png
  static/img/channelPic-heart.png
  static/img/channelPic-heartLine.png
  static/img/edit-hover.png
  static/img/edit.png
  static/img/myPage-Black.png
  static/img/myPage-White.png
  static/img/userIcon.png
  templates/modal/update-name-email.html
  templates/modal/update-password.html
  templates/my_page.html
Labels: frontend, backend

#35 mypageのヘッダー部分はみ出し変更、ログイン画面スクロールしないように変更
  .vscode/settings.json
  static/css/login.css
  static/css/my_page.css
Labels: frontend

#40 機密情報のソフトコーディング、logoutモーダル追加、モーダルキャンセルボタン追加
  app.py
  k.txt
  sectxt.json
  static/js/modal.js
  static/js/update-channel.js
  static/js/update-mypage.js
  templates/detail.html
  templates/index.html
  templates/modal/add-channel.html
  templates/modal/add-reaction.html
  templates/modal/delete-channel.html
  templates/modal/delete-message.html
  templates/modal/follow-channel.html
  templates/modal/logout.html
  templates/modal/unfollow-channel.html
  templates/modal/update-channel.html
  templates/modal/update-message.html
  templates/modal/update-name-email.html
  templates/modal/update-password.html
  templates/my_page.html
  util/DB.py
  util/crypto_dec.py
Labels: backend

#41 ログイン、サインアップ画面修正。ログイン画面実装。
  static/css/home.css
  static/css/login.css
  static/css/my_page.css
  static/css/sign-up.css
  static/img/Home.png
  static/img/trashIcon.png
  static/js/pagination.js
  templates/index.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: frontend

#44 モーダル実装、マイページちょっと変更加えた
  static/css/home.css
  static/css/modal.css
  static/css/my_page.css
  static/img/creatChannel-hover.png
  static/img/creatChannel.png
  static/img/modal-channelAddWhite.png
  static/img/modal-editWhite.png
  static/img/modal-heartPlusWhite.png
  static/img/modal-heartminusWhite.png
  static/img/modal-logoutWhite.png
  static/img/modal-trashWhite.png
  templates/index.html
  templates/modal/add-channel.html
  templates/modal/add-reaction.html
  templates/modal/delete-channel.html
  templates/modal/delete-message.html
  templates/modal/follow-channel.html
  templates/modal/logout.html
  templates/modal/unfollow-channel.html
  templates/modal/update-channel.html
  templates/modal/update-message.html
  templates/modal/update-name-email.html
  templates/modal/update-password.html
Labels: frontend

#46 Feature＃38
  static/css/chatroom.css
  static/css/detail.css
  static/img/channelEditB-hover.png
  static/img/channelEditB.png
  static/img/chatBlack.png
  static/img/chatSendB-hover.png
  static/img/chatSendB.png
  static/img/messageEdit-hover.png
  static/img/messageEdit.png
  static/img/reactionPlusB-hover.png
  static/img/reactionPlusB.png
  static/img/trashB-hover.png
  static/img/trashB.png
  static/img/userB-hover.png
  static/img/userB.png
  static/js/update-channel.js
  templates/detail.html
Labels: frontend

#55 pythonのreturnは基本redirectに変更
  app.py
  k.txt
  sectxt.json
  static/js/scroll-message.js
  templates/detail.html
  templates/error/404.html
  templates/error/500.html
  templates/error/error.html
  util/DB.py
  util/crypto_dec.py
Labels: backend

#57 チャット画面モーダル表示修正、チャンネル名等表示修正
  static/css/home.css
  static/css/modal.css
  static/css/my_page.css
  templates/detail.html
  templates/modal/update-channel.html
Labels: frontend

#60 仮googleログインページ作成
  app.py
  templates/registration/google-login.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: frontend, backend

#65 デプロイ時に影響が出る箇所を修正
  app.py
  static/css/login.css
  static/css/my_page.css
  static/css/sign-up.css
  templates/error/500.html
Labels: frontend, backend

#67 Feature#49
  app.py
  models.py
  static/css/chatroom.css
  static/css/home.css
  static/css/login.css
  static/css/my_page.css
  static/css/sign-up.css
  templates/detail.html
  templates/my_page.html
Labels: frontend, backend

#68 ユーザアイコン暫定版追加
  app.py
  init.sql
  models.py
  static/css/modal.css
  static/img/user-icon/apple.png
  static/img/user-icon/chinese-cabbage.png
  static/img/user-icon/corn.png
  static/img/user-icon/lemon.png
  static/img/user-icon/orange.png
  static/img/user-icon/peach.png
  static/img/user-icon/pineapple.png
  static/img/user-icon/pumpkin.png
  static/img/user-icon/spinach.png
  static/img/user-icon/straberry.png
  static/img/user-icon/userIcon.png
  static/js/update-mypage.js
  templates/detail.html
  templates/modal/add-reaction.html
  templates/modal/update-Icon.html
  templates/my_page.html
Labels: backend

#73 Googleloginボタン押したときのCSS完了
  static/css/google-login.css
  static/img/google-login-haikei.png
  templates/registration/google-login.html
Labels: frontend

#74 Feature#47
  static/css/chatroom.css
  static/css/detail.css
  templates/detail.html
  templates/my_page.html
Labels: frontend

#76 mypage画面のアイコン変更、アイコン選択のモーダルの修正、リアクションのモーダル画像修正
  static/css/modal.css
  static/css/my_page.css
  static/img/changeIconB.png
  static/img/changeIconB.png-hover.png
  static/img/modal-UserWhite.png
  static/img/modal-reactionWhite.png
  templates/modal/add-reaction.html
  templates/modal/update-Icon.html
  templates/my_page.html
Labels: frontend

#77 チャットメッセージにユーザアイコンを追加
  app.py
  models.py
  static/css/modal.css
  static/css/my_page.css
  static/js/detail-modal.js
  templates/detail.html
Labels: backend

#79 ログイン、サインイン画面の全体の位置修正、googleロゴ位置修正、ファビコン実装
  static/css/login.css
  static/css/sign-up.css
  static/img/ring-favicon.ico
  templates/base.html
  templates/registration/base.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: frontend

#82 mypage画面、User Nameの位置修正
  static/css/modal.css
  static/css/my_page.css
  templates/my_page.html
Labels: frontend

#83 Feature#71
  static/css/error.css
  static/img/404.png
  static/img/500.png
  static/img/ERROR.png
  templates/error/404.html
  templates/error/500.html
  templates/error/error.html
Labels: frontend

#84 チャット画面のユーザーアイコン修正とMyPageのスクロール非表示に修正
  static/css/chatroom.css
  static/css/detail.css
  static/css/my_page.css
  templates/detail.html
Labels: frontend

#85 入力値の文字数制限追加
  app.py
  static/css/detail.css
  templates/detail.html
Labels: backend

#91 ERROR画面修正しました
  static/css/error.css
  templates/error/base.html
  templates/error/error.html
Labels: frontend

#92 微調整
  static/css/error.css
  static/css/modal.css
  templates/error/404.html
  templates/error/500.html
  templates/error/base.html
  templates/error/error.html
Labels: frontend

#94 エラー画面の微調整
  static/css/error.css
  templates/error/error.html
Labels: frontend
